global_costmap:
   global_frame: map
   width: 8.0
   height: 8.0
   resolution: 0.1
   static_map: true
   rolling_window: false
   track_unknown_space: true
   plugins:
     - {name: static,    type: "costmap_2d::StaticLayer"}
     - {name: inflation, type: "costmap_2d::InflationLayer"}
