local_costmap:
   global_frame: odom
   width: 3.0
   height: 3.0
   resolution: 0.1
   static_map: false
   rolling_window: true
   plugins:
     - {name: obstacles, type: "costmap_2d::ObstacleLayer"}
     - {name: inflation, type: "costmap_2d::InflationLayer"}
