<?xml version='1.0'?>

<robot name="my_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">
<xacro:include filename="$(find my_robot)/urdf/my_robot.gazebo" />

<xacro:property name="length" value="0.5" />
<xacro:property name="width" value="0.3" />
<xacro:property name="length_middle" value="${length-0.05}" />
<xacro:property name="width_middle" value="${width-0.05}" />
<xacro:property name="height_bottom" value="0.16" />
<xacro:property name="height_middle" value="0.02" />
<xacro:property name="height_top" value="0.02" />
<xacro:property name="wheel_radius" value="0.12" />
<xacro:property name="wheel_thickness" value="0.05" />
<xacro:property name="caster_wheel_radius" value="0.06" />
<xacro:property name="lift" value="0.1" />

  <link name="robot_footprint"></link>

  <joint name="robot_footprint_joint" type="fixed">
    <origin xyz="0 ${lift} 0" rpy="0 0 0" />
    <parent link="robot_footprint"/>
    <child link="chassis" />
  </joint>

  <link name="chassis">
    <inertial>
      <mass value="100.0"/>
      <origin xyz="0.0 0 0" rpy=" 0 0 0"/>
      <inertia
          ixx="0.1" ixy="0" ixz="0"
          iyy="0.1" iyz="0"
          izz="0.1"
      />
    </inertial>

    <collision name='chassis_bottom_collision'>
      <origin xyz=" 0 0 ${height_bottom/2}" rpy=" 0 0 0"/>
      <geometry>
        <box size="${length} ${width} ${height_bottom}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz=" 0 0 ${height_bottom/2}" rpy=" 0 0 0"/>
      <geometry>
        <box size="${length} ${width} ${height_bottom}"/>
      </geometry>
      <material name="silver"/>
    </visual>

    <collision name='chassis_middle_collision'>
      <origin xyz="0 0 ${height_bottom+height_middle/2}" rpy=" 0 0 0"/>
      <geometry>
        <box size="${length_middle} ${width_middle} ${height_middle}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${height_bottom+height_middle/2}" rpy=" 0 0 0"/>
      <geometry>
        <box size="${length_middle} ${width_middle} ${height_middle}"/>
      </geometry>
      <material name="silver"/>
    </visual>

    <collision name='chassis_top_collision'>
      <origin xyz="0 0 ${height_bottom+height_middle+height_top/2}" rpy=" 0 0 0"/>
      <geometry>
        <box size="${length} ${width} ${height_top}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${height_bottom+height_middle+height_top/2}" rpy=" 0 0 0"/>
      <geometry>
        <box size="${length} ${width} ${height_top}"/>
      </geometry>
      <material name="silver"/>
    </visual>

    <collision name="caster_wheel_collision">
      <origin xyz="${-(length/2-(0.04+caster_wheel_radius))} 0 ${-(lift-caster_wheel_radius)}" rpy=" 0 0 0"/>
      <geometry>
        <sphere radius="${caster_wheel_radius}"/>
      </geometry>
      <surface>
        <friction>
          <ode>
            <mu>0</mu>
            <mu2>0</mu2>
            <slip1>1.0</slip1>
            <slip2>1.0</slip2>
          </ode>
        </friction>
      </surface>
    </collision>

    <visual>
      <origin xyz="${-(length/2-(0.04+caster_wheel_radius))} 0 ${-(lift-caster_wheel_radius)}" rpy=" 0 0 0"/>
      <geometry>
        <sphere radius="${caster_wheel_radius}"/>
      </geometry>
      <material name="silver"/>
    </visual>

  </link>

  <xacro:macro name="wheels" params="side reflect">
    <joint type="continuous" name="${side}_wheel_hinge">
     <origin xyz="${length/2-(0.05+wheel_radius)} ${reflect*(width + wheel_thickness)/2} ${-(lift-wheel_radius)}" rpy="0 0 0"/>
     <child link="${side}_wheel"/>
     <parent link="chassis"/>
     <axis xyz="0 1 0" rpy="0 0 0"/>
     <limit effort="10000" velocity="1000"/>
     <dynamics damping="1.0" friction="1.0"/>
   </joint>

   <link name="${side}_wheel">
      <inertial>
        <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
        <mass value="5"/>
        <inertia
            ixx="0.02" ixy="0" ixz="0"
            iyy="0.02" iyz="0"
            izz="0.04"
        />
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
        </geometry>
        <material name="black"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
        </geometry>
      </collision>
    </link>
  </xacro:macro>

  <xacro:wheels side="left" reflect="1" />
  <xacro:wheels side="right" reflect="-1" />

  <joint type="fixed" name="camera_joint">
   <origin xyz="${length/2 + 0.05/4} 0 ${height_bottom/2}" rpy="0 0 0"/>
   <child link="camera"/>
   <parent link="chassis"/>
 </joint>

 <link name="camera">
   <inertial>
     <origin xyz="0.05 0.05 0.05" rpy="0 0 0"/>
     <mass value="0.1"/>
     <inertia
         ixx="1e-6" ixy="0" ixz="0"
         iyy="1e-6" iyz="0"
         izz="1e-6"
     />
   </inertial>
   <visual>
     <origin xyz="0 0 0" rpy="0 0 0"/>
     <geometry>
       <box size="0.05 0.05 0.05"/>
     </geometry>
     <material name="red"/>
   </visual>
   <collision>
     <origin xyz="0 0 0" rpy="0 0 0"/>
     <geometry>
       <box size="0.05 0.05 0.05"/>
     </geometry>
   </collision>
 </link>

 <joint name="camera_optical_joint" type="fixed">
   <origin xyz="0 0 0" rpy="-1.5707 0 -1.5707"/>
   <parent link="camera"/>
   <child link="camera_link_optical"/>
 </joint>

 <link name="camera_link_optical">
 </link>

 <joint type="fixed" name="hokuyo_joint">
  <origin xyz=" ${length/2-(0.05+0.1/2)} 0 ${height_bottom+height_middle+height_top+0.1/2}" rpy="0 0 0"/>
  <child link="hokuyo"/>
  <parent link="chassis"/>
</joint>

<link name="hokuyo">
  <inertial>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <mass value="1e-5"/>
    <inertia
        ixx="1e-6" ixy="0" ixz="0"
        iyy="1e-6" iyz="0"
        izz="1e-6"
    />
  </inertial>
  <visual>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
      <mesh filename="package://my_robot/meshes/hokuyo.dae"/>
    </geometry>
    <material name="black"/>
  </visual>
  <collision>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
      <box size="0.1 0.1 0.1"/>
    </geometry>
  </collision>
</link>

<joint name="imu_joint" type="fixed">
  <origin xyz="0 0 0" rpy="0 0 0"/>
  <parent link="robot_footprint"/>
  <child link="imu_link"/>
</joint>

<link name="imu_link">
</link>

<material name="silver">
  <color rgba="0.75 0.75 0.75 1"/>
</material>

<material name="red">
  <color rgba="1 0 0 1"/>
</material>

<material name="black">
  <color rgba="0 0 0 1"/>
</material>

<gazebo reference="chassis">
    <material>Gazebo/DarkGrey</material>
</gazebo>

<gazebo reference="camera">
    <material>Gazebo/Red</material>
</gazebo>

<gazebo reference="left_wheel">
    <material>Gazebo/Black</material>
</gazebo>

<gazebo reference="right_wheel">
    <material>Gazebo/Black</material>
</gazebo>

</robot>
